### ISSUE TITLE
Make "Name" useful

### ISSUE THREAD

**Issue by chriskuech** [microsoft/Requirements#35]
# Goals
- [ ] Consistent behavior across formatters
- [ ] Requirement composition with namespacing

# Tasks
- [ ] Implement `Push-Requirement [-Namespace] <string> [[-Requirements] <Requirements[]>] [[-ScriptBlock] <ScriptBlock>]` for composing arrays of requirements, automatically prefixing the `Name` property of the `Requirements` with `Namespace`.
- [ ] Consistent use of `Name` vs `Description` in formatters
- [ ] Deprecate nested Requirements
- [ ] Update README with modified patterns

**Comment by chriskuech** [comment]
Not sure how to handle namespace delimiters

**Comment by chriskuech** [comment]
#46
